# Site settings
title: Momoe Nomoto
description: Jekyll Theme Minimal Resume
# baseurl: /momoenomoto.github.io # the subpath of your site, e.g. /blog
url: https://momoenomoto.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Momoe Nomoto
user_description: Student at NYU Shanghai, double majoring in Computer Science and Electrical and Systems Engineering. Passionate about building robots.
user_title: Potential Engineer
email: mn2668@nyu.edu
# twitter_username: lorem_ipsum
github_username:  momoenomoto
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
