# Site settings
title: Momoe Nomoto
description: Jekyll Theme Minimal Resume
baseurl: /momoenomoto.github.io # the subpath of your site, e.g. /blog
url: https://momoenomoto.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Momoe Nomoto
user_description: Working on things right now. 
user_title: Potential Engineer
email: mn2668@nyu.edu or momoe.nomoto.mn@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
